name: lite-mono
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - blas=1.0
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.1.3
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - contourpy=1.0.7
  - cryptography=39.0.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2023.3.2
  - dbus=1.13.18
  - expat=2.5.0
  - ffmpeg=4.3
  - filelock=3.9.0
  - flit-core=3.8.0
  - fontconfig=2.14.1
  - fonttools=4.39.3
  - freetype=2.12.1
  - fsspec=2023.3.0
  - gcc_impl_linux-64=12.1.0
  - gcc_linux-64=12.1.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gxx_impl_linux-64=12.1.0
  - gxx_linux-64=12.1.0
  - huggingface_hub=0.13.3
  - icu=58.2
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.26.1
  - importlib-metadata=6.1.0
  - importlib_metadata=6.1.0
  - intel-openmp=2021.4.0
  - jinja2=3.1.2
  - jpeg=9e
  - jxrlib=1.1
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=10.0.1
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.6.0.25
  - libcurand=10.3.2.56
  - libcurl=7.87.0
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-devel_linux-64=12.1.0
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libnghttp2=1.46.0
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libpq=12.9
  - libprotobuf=3.20.3
  - libsanitizer=12.1.0
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=12.1.0
  - libstdcxx-ng=12.2.0
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - munkres=1.1.4
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=2.8.4
  - nspr=4.35
  - nss=3.74
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1t
  - packaging=23.0
  - partd=1.3.0
  - pcre=8.45
  - pillow=9.4.0
  - pip=23.0.1
  - ply=3.11
  - pooch=1.6.0
  - protobuf=3.20.3
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pysocks=1.7.1
  - python=3.10.10
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=2.0.0
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pywavelets=1.4.1
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.28.1
  - scikit-image=0.19.2
  - scipy=1.8.1
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.41.1
  - sympy=1.11.1
  - sysroot_linux-64=2.12
  - tensorboardx=2.2
  - tifffile=2021.4.8
  - timm=0.6.13
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - torchtriton=2.0.0
  - torchvision=0.15.0
  - tornado=6.2
  - tqdm=4.65.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - unicodedata2=15.0.0
  - urllib3=1.26.14
  - wheel=0.38.4
  - xz=5.2.10
  - yaml=0.2.5
  - zfp=0.5.5
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - linear-warmup-cosine-annealing-warm-restarts-weight-decay==1.0
    - mpmath==1.2.1
    - pyqt5-sip==12.11.0
